version: "3.7"
services: 
  # Microservice
  app_companies:
    build: 
      args:
        user: app_companies
        uid: 1000
      context: ./
      dockerfile: Dockerfile 
    image: laravel-app
    restart: unless-stopped
    depends_on:
      - redis
    working_dir: /var/www/
    volumes: 
      - ./:/var/www
    networks: 
      - companies_service
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Servidor nginx
  nginx: 
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
      - 443:443
    volumes: 
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks: 
      - companies_service

  # Database mysql companies
  db_companies: 
    image: mysql:8.0.29
    restart: unless-stopped
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3333:3306
    volumes: 
      - ./.docker/mysql/dbdata:/var/lib/mysql
    networks: 
      - companies_service

  # Queue
  queue:
    build: 
      args:
        user: app_companies
        uid: 1000
      context: ./
      dockerfile: Dockerfile 
    restart: unless-stopped
    command: "php artisan queue:work"
    depends_on:
      - redis
    volumes: 
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks: 
      - companies_service

  # Redis
  redis: 
    image: redis:latest
    networks:
      - companies_service

networks:
  companies_service: 
    driver: bridge