version: "3.7"
services: 
  # Microservice
  laraservice:
    build: 
      args:
        user: laraservice
        uid: 1000
      context: ./
      dockerfile: Dockerfile 
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes: 
      - ./:/var/www
    networks: 
      - microservices
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Servidor nginx
  nginx: 
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
      - 443:443
    volumes: 
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks: 
      - microservices

  # Database mysql laraservice
  db_laraservice: 
    image: mysql:8.0.29
    restart: unless-stopped
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3333:3306
    volumes: 
      - ./.docker/mysql/dbdata:/var/lib/mysql
    networks: 
      - microservices

networks:
  microservices: 
    driver: bridge